language: android
mono:
  - latest
sudo: true
env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
addons:
  apt:
    packages:
      - libglew-dev
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - xserver-xorg-video-dummy
      - xpra
      - xorg-dev
      - opencl-headers
      - libgl1-mesa-dev
      - libxcursor-dev
      - libpulse-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxv-dev
      - libasound2-dev
      - libudev-dev
      - mesa-utils
      - libgl1-mesa-glx
      - libgles2-mesa-dev
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_script:
  - android-update-sdk --components=sys-img-armeabi-v7a-android-21 --accept-licenses='android-sdk-license-[0-9a-f]{8}'
script: ./gradlew clean build
