language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - build-tools-27.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu on &
  - android-wait-for-emulator
