language: android
sudo: true
env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.mono-project.com/repo/ubuntu stable-trusty main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF'
    packages:
      - mono-complete
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get update
  - sudo apt-get install gtk-sharp3
before_script:
  - android-update-sdk --components=sys-img-armeabi-v7a-android-21 --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - curl -O https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/monogame-sdk.run
  - chmod +x monogame-sdk.run
  - sudo ./monogame-sdk.run --noexec --keep --target ./monogame
  - sudo chmod 777 ./monogame/postinstall.sh
  - cp Build/postinstall.sh ./monogame
  - cd monogame
  - sudo chmod +x postinstall.sh
  - sudo ./postinstall.sh
  - cd ..
script: ./gradlew clean build --stacktrace
