language: android
sudo: true
env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_script:
  - yes | sdkmanager --update
script: ./gradlew  clean build --stacktrace -x :mini2Dx-uats-libgdx-android:check -x :mini2Dx-uats-libgdx-android:validateSigningDebug -x :mini2Dx-uats-libgdx-android:packageDebug
