language: android
sudo: true
env:
  global:
    - ADB_INSTALL_TIMEOUT=5 # minutes
addons:
  apt:
    packages:
      - libglew-dev
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - xserver-xorg-video-dummy
      - xpra
      - xorg-dev
      - opencl-headers
      - libgl1-mesa-dev
      - libxcursor-dev
      - libpulse-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxv-dev
      - libasound2-dev
      - libudev-dev
      - mesa-utils
      - libgl1-mesa-glx
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ce63b0ed77e8bf5dc74
    on_success: change
    on_failure: always
    on_start: false
  email:
    on_success: change
    on_failure: always
before_install:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  - sudo apt-get update -qq --force-yes
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-utils mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb
  #- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - sleep 3 
  - LIBGL_ALWAYS_SOFTWARE=1 glxinfo
  - glxinfo
before_script:
  - android-update-sdk --components=sys-img-armeabi-v7a-android-21 --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -gpu on
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
